[redis]
connection-string = "redis://localhost:6379/0"

[couch]
host = "http://localhost:5984"
username = "admin"
password = "pw"
db.spriteib = "spriteib"
db.listing = "spriteib_listing"

[spriteib]
run.host = "127.0.0.1:3000"
post.op.max-length = 5000
post.op.max-file-size = 10000000
post.comment.max-length = 2000
post.comment.max-file-size = 5000000
thread.max-comments = 400
board.max-threads = 150
